[package]
name = "thrift-tutorial-pool"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thrift = "0.15.0"
thrift-pool = "0.1.4"
